In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(units = 2, activation = 'relu', input_dim = 2))
model.add(Dense(units=1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = 'accuracy')

X = np.array([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
print("Input data:")
print(X)

y = np.array([0.,1.,1.,0.])
print("\nTarget labels:")
print(y)

print("*"*30)

model.get_weights()
model.fit(X,y,epochs = 500)
predictions = model.predict(X)
print("\nPredictions after training:")
print(predictions)

Input data:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]

Target labels:
[0. 1. 1. 0.]
******************************
Epoch 1/500
1/1 [==============================] - 1s 985ms/step - loss: 0.6316 - accuracy: 0.7500
Epoch 2/500
1/1 [==============================] - 0s 11ms/step - loss: 0.6314 - accuracy: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 11ms/step - loss: 0.6312 - accuracy: 0.7500
Epoch 4/500
1/1 [==============================] - 0s 12ms/step - loss: 0.6309 - accuracy: 0.7500
Epoch 5/500
1/1 [==============================] - 0s 13ms/step - loss: 0.6306 - accuracy: 0.7500
Epoch 6/500
1/1 [==============================] - 0s 12ms/step - loss: 0.6303 - accuracy: 0.7500
Epoch 7/500
1/1 [==============================] - 0s 12ms/step - loss: 0.6300 - accuracy: 0.7500
Epoch 8/500
1/1 [==============================] - 0s 11ms/step - loss: 0.6298 - accuracy: 0.7500
Epoch 9/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6295 - accuracy: 0.7500
Epoch 1

In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

# Define the model architecture
model = Sequential()
model.add(Dense(units=2, activation='relu', input_dim=2))
model.add(Dense(units=1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics='accuracy')

# Define input data
X = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
print("Input data:")
print(X)

# Define target labels
y = np.array([0., 1., 1., 0.])
print("\nTarget labels:")
print(y)

# Retrieve initial weights of the model
initial_weights = model.get_weights()
print("\nInitial weights of the model:")
for layer_weights in initial_weights:
    print(layer_weights)

# Train the model
model.fit(X, y, epochs=500, verbose=0)
print("\nTraining completed.")

# Get predictions
predictions = model.predict(X)
print("\nPredictions after training:")
print(predictions)


Input data:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]

Target labels:
[0. 1. 1. 0.]

Initial weights of the model:
[[-1.0974654   0.7102518 ]
 [-0.43969333 -0.88038176]]
[0. 0.]
[[0.76796925]
 [0.05321562]]
[0.]

Training completed.
1/1 [==============================] - 0s 49ms/step

Predictions after training:
[[0.45517626]
 [0.45517626]
 [0.63469446]
 [0.45517626]]


In [ ]:
!pip install keras
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
names =["No. of pregnancies","Glucose level","Blood Pressure","skin thickness","Insulin","BMI","Diabetes pedigree","Age","Class"]
df=pd.read_csv("/content/pima-indians-diabetes.data.csv",names = names)
df.head(3)
binaryc = Sequential()
from tensorflow.tools.docs.doc_controls import doc_in_current_and_subclasses
binaryc.add(Dense(units=10,activation='relu',input_dim=8))
binaryc.add(Dense(units=8,activation='relu'))
binaryc.add(Dense(units=1,activation='sigmoid'))
binaryc.compile(loss='binary_crossentropy',optimizer='adam',metrics="accuracy")
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size = 0.25, random_state=1)
xtrain.shape
ytrain.shape
binaryc.fit(xtrain,ytrain,epochs=200,batch_size=20)
predictions=binaryc.predict(xtest)
predictions.shape
class_labels=[]
for i in predictions:
  if(i>0.5):
    class_labels.append(1)
  else:
    class_labels.append(0)
class_labels
from sklearn.metrics import accuracy_score
print('Accuracy Score', accuracy_score(ytest,class_labels))

Epoch 1/200
29/29 [==============================] - 1s 2ms/step - loss: 6.9826 - accuracy: 0.6458
Epoch 2/200
29/29 [==============================] - 0s 2ms/step - loss: 3.7636 - accuracy: 0.6302
Epoch 3/200
29/29 [==============================] - 0s 2ms/step - loss: 1.7955 - accuracy: 0.5920
Epoch 4/200
29/29 [==============================] - 0s 2ms/step - loss: 1.0771 - accuracy: 0.5104
Epoch 5/200
29/29 [==============================] - 0s 2ms/step - loss: 0.8779 - accuracy: 0.5382
Epoch 6/200
29/29 [==============================] - 0s 2ms/step - loss: 0.7689 - accuracy: 0.6181
Epoch 7/200
29/29 [==============================] - 0s 2ms/step - loss: 0.7364 - accuracy: 0.6059
Epoch 8/200
29/29 [==============================] - 0s 2ms/step - loss: 0.7237 - accuracy: 0.6267
Epoch 9/200
29/29 [==============================] - 0s 2ms/step - loss: 0.6880 - accuracy: 0.6354
Epoch 10/200
29/29 [==============================] - 0s 2ms/step - loss: 0.6618 - accuracy: 0.6441
Epoch 11/

6/6 [==============================] - 0s 4ms/step
Accuracy Score 0.7239583333333334
