Aim: Using feed Forward Network with multiple hidden layers for performing multiclass classification and predicting the class. 

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/flower_1.csv")

In [ ]:
df.head()

sepal length  sepal width  petal length  petal width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
x=df.iloc[:,:-1].astype(float)
y=df.iloc[:,-1]

In [ ]:
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [ ]:
#labelencode y
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
import numpy as np
from tensorflow.keras.utils import to_categorical
#from keras.utils import np_utils
encoded_Y = to_categorical(y)
encoded_Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
#creating a model
model = Sequential()

model.add(Dense(units = 10, activation = 'relu', input_dim = 4))
model.add(Dense(units = 8, activation = 'relu'))
model.add(Dense(units = 3, activation = 'softmax'))

model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])


In [ ]:
model.fit(x,encoded_Y,epochs = 400,batch_size = 10)

Epoch 1/400
15/15 [==============================] - 1s 2ms/step - loss: 0.9317 - accuracy: 0.5667
Epoch 2/400
15/15 [==============================] - 0s 2ms/step - loss: 0.8876 - accuracy: 0.7400
Epoch 3/400
15/15 [==============================] - 0s 2ms/step - loss: 0.8599 - accuracy: 0.8133
Epoch 4/400
15/15 [==============================] - 0s 3ms/step - loss: 0.8271 - accuracy: 0.8200
Epoch 5/400
15/15 [==============================] - 0s 2ms/step - loss: 0.7971 - accuracy: 0.8333
Epoch 6/400
15/15 [==============================] - 0s 2ms/step - loss: 0.7668 - accuracy: 0.8667
Epoch 7/400
15/15 [==============================] - 0s 2ms/step - loss: 0.7361 - accuracy: 0.8467
Epoch 8/400
15/15 [==============================] - 0s 3ms/step - loss: 0.7017 - accuracy: 0.8667
Epoch 9/400
15/15 [==============================] - 0s 2ms/step - loss: 0.6714 - accuracy: 0.8800
Epoch 10/400
15/15 [==============================] - 0s 2ms/step - loss: 0.6435 - accuracy: 0.8800
Epoch 11/

In [ ]:
predict = model.predict(x)
print(predict)

5/5 [==============================] - 0s 3ms/step
[[9.99892890e-01 1.07018706e-04 1.32209188e-10]
 [9.99642253e-01 3.57709854e-04 1.26742605e-09]
 [9.99786139e-01 2.13804553e-04 6.71566025e-10]
 [9.99652267e-01 3.47720372e-04 1.88830906e-09]
 [9.99912322e-01 8.75762053e-05 1.08324641e-10]
 [9.99918520e-01 8.13577863e-05 7.71243555e-11]
 [9.99810696e-01 1.89447208e-04 7.15721371e-10]
 [9.99844790e-01 1.55344882e-04 2.93406632e-10]
 [9.99479115e-01 5.20752685e-04 4.57105420e-09]
 [9.99737978e-01 2.62016896e-04 7.31889438e-10]
 [9.99930561e-01 6.93932743e-05 4.55848380e-11]
 [9.99815464e-01 1.84526987e-04 5.33511235e-10]
 [9.99697089e-01 3.02930654e-04 1.01164832e-09]
 [9.99750853e-01 2.49192613e-04 1.22687416e-09]
 [9.99977887e-01 2.20333568e-05 3.48109627e-12]
 [9.99981105e-01 1.88250651e-05 4.18200067e-12]
 [9.99948323e-01 5.16129185e-05 2.99192372e-11]
 [9.99869823e-01 1.30119632e-04 1.98429329e-10]
 [9.99922812e-01 7.71303676e-05 4.37025069e-11]
 [9.99926746e-01 7.31965338e-05 8.044

In [ ]:
for i in range(35,150,3):
    print(predict[i],encoded_Y[i])

[9.9982524e-01 1.7481401e-04 3.0830541e-10] [1. 0. 0.]
[9.9963063e-01 3.6942022e-04 2.4676887e-09] [1. 0. 0.]
[9.944791e-01 5.520707e-03 1.215596e-07] [1. 0. 0.]
[9.9985981e-01 1.4028362e-04 3.1122951e-10] [1. 0. 0.]
[9.9975336e-01 2.4665910e-04 1.0193524e-09] [1. 0. 0.]
[1.8988330e-05 9.9971485e-01 2.6625267e-04] [0. 1. 0.]
[2.7946558e-05 9.8449421e-01 1.5477814e-02] [0. 1. 0.]
[2.6917556e-05 9.9367619e-01 6.2968601e-03] [0. 1. 0.]
[1.2282775e-04 9.9106300e-01 8.8141169e-03] [0. 1. 0.]
[4.8567614e-05 9.9911880e-01 8.3257275e-04] [0. 1. 0.]
[3.9489714e-05 9.9964404e-01 3.1653879e-04] [0. 1. 0.]
[1.7772327e-06 7.2758049e-01 2.7241790e-01] [0. 1. 0.]
[1.0159923e-04 9.9934751e-01 5.5085646e-04] [0. 1. 0.]
[4.8856567e-05 9.9948770e-01 4.6337864e-04] [0. 1. 0.]
[3.1058748e-06 8.7283760e-01 1.2715934e-01] [0. 1. 0.]
[1.5545625e-04 9.9866450e-01 1.1800390e-03] [0. 1. 0.]
[4.6027105e-07 5.9818909e-02 9.4018060e-01] [0. 1. 0.]
[9.2509972e-06 9.9892491e-01 1.0657739e-03] [0. 1. 0.]
[4.850590e-05

In [ ]:
actual = []

for i in range(0,150):
    actual.append(np.argmax(predict[i]))

print(actual)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [ ]:
newdf = pd.DataFrame(list(zip(actual,y)),columns = ['Actual','Predicted'])
newdf

Actual  Predicted
0         0          0
1         0          0
2         0          0
3         0          0
4         0          0
..      ...        ...
145       2          2
146       2          2
147       2          2
148       2          2
149       2          2

[150 rows x 2 columns]