## 10 A) Aim:  Implement the different Distance methods (Euclidean) with Prediction, Test Score and Confusion Matrix. 

In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [13]:
#Load the dataset
df = pd.read_csv("../dataset/Iris.csv")

#quick look into the data
print(df.head(5))
print("\n")

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa




In [14]:
#Separate data and label
x = df.drop(['Species'], axis=1)
y = df['Species']

#Prepare data for classification process
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [15]:
#Create a model , p = 2 => Euclidean Distance:
knn = KNeighborsClassifier(n_neighbors = 6, p = 2, metric='minkowski')

#Train the model
knn.fit(x_train, y_train)

# Calculate the accuracy of the model
print("Accuracy of Euclidean Distance model:-")
print(knn.score(x_test, y_test))
y_pred = knn.predict(x_test)

#confusion matrix 
from sklearn.metrics import  confusion_matrix
cm=np.array(confusion_matrix(y_test,y_pred))
print("-"*50)
print("Confusion matrix:-")
print(cm)
print("\n")

Accuracy of Euclidean Distance model:-
0.9777777777777777
--------------------------------------------------
Confusion matrix:-
[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]




In [16]:
#Create a model , p = 1 => Manhattan Distance
knn = KNeighborsClassifier(n_neighbors = 6, p = 1, metric='minkowski')

#Train the model
knn.fit(x_train, y_train)

# Calculate the accuracy of the model
print("-"*50)
print("Accuracy of Manhattan Distance model:-")
print(knn.score(x_test, y_test))
y_pred = knn.predict(x_test)

#confusion matrix 
from sklearn.metrics import  confusion_matrix
cm=np.array(confusion_matrix(y_test,y_pred))
print("-"*50)
print("Confusion matrix:-")
print(cm)
print("\n")

--------------------------------------------------
Accuracy of Manhattan Distance model:-
0.9555555555555556
--------------------------------------------------
Confusion matrix:-
[[16  0  0]
 [ 0 17  1]
 [ 0  1 10]]




In [18]:
#Create a model ,p = ∞, Chebychev Distance
#let ∞ = 10000
knn = KNeighborsClassifier(n_neighbors = 6, p = 10000, metric='minkowski')

#Train the model
knn.fit(x_train, y_train)

# Calculate the accuracy of the model
print("-"*50)
print("Accuracy of Chebychev Distance model:-")
print(knn.score(x_test, y_test))
y_pred = knn.predict(x_test)

#confusion matrix 
from sklearn.metrics import  confusion_matrix
cm=np.array(confusion_matrix(y_test,y_pred))
print("-"*50)
print("Confusion matrix:-")
print(cm)
print("\n") 


--------------------------------------------------
Accuracy of Chebychev Distance model:-
0.8
--------------------------------------------------
Confusion matrix:-
[[16  0  0]
 [ 0 18  0]
 [ 0  9  2]]


