# 9. Implement Naive Bayes classifier

In [3]:
# pip install pandas
# pip install sklearn
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Download NLTK stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [4]:
# Read the SMS data
sms_data = pd.read_csv("/content/spam.csv", encoding='latin-1')

# Initialize the Porter Stemmer
stemming = PorterStemmer()
corpus = []

# Create the corpus with stemmed words
for i in range(len(sms_data)):
    s1 = re.sub('[^a-zA-Z]', ' ', sms_data['v2'][i])
    s1 = s1.lower()
    s1 = s1.split()
    s1 = [stemming.stem(word) for word in s1 if word not in set(stopwords.words('english'))]
    s1 = ' '.join(s1)
    corpus.append(s1)

# Convert the corpus into a matrix of token counts
countvectorizer = CountVectorizer()
x = countvectorizer.fit_transform(corpus).toarray()
print(x)



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
# Extract the target variable
y = sms_data['v1'].values
print(y)

['ham' 'ham' 'spam' ... 'ham' 'ham' 'ham']


In [6]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify=y, random_state=2)

# Initialize the Multinomial Naïve Bayes model
multinomialnb = MultinomialNB()
multinomialnb.fit(x_train, y_train)

# Predicting on test data
y_pred = multinomialnb.predict(x_test)
print(y_pred)

['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']


In [7]:
# Results of our models
print(classification_report(y_test, y_pred))
print("accuracy_score: ", accuracy_score(y_test, y_pred))


              precision    recall  f1-score   support

         ham       0.99      0.98      0.99      1448
        spam       0.89      0.92      0.91       224

    accuracy                           0.97      1672
   macro avg       0.94      0.95      0.95      1672
weighted avg       0.98      0.97      0.98      1672

accuracy_score:  0.9748803827751196
